<a href="https://colab.research.google.com/github/SayanBapariAI/Pytorch-Tutorial/blob/main/pytoch_tutorial_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch


In [ ]:
torch.__version__


'2.0.1+cu118'

### Range

In [ ]:
torch.range(1,10)

<ipython-input-5-a2647884754e>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.arange(start=1,end=11, step=2)

tensor([1, 3, 5, 7, 9])

In [ ]:
rangeing = torch.arange(1,11)
rangeing


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
rangeing = torch.arange(start=1,end=11)
rangeing


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
rangeing = torch.arange(start=1,end=11, step=2)
rangeing

tensor([1, 3, 5, 7, 9])

### Matrix MUltiplication



Two main ways of performing multiplications in neural network

1. **Inner dimension** must match

* ` (3,2) @ (3,2) ` won't work
* ` (2,3) @ (3,2) ` will work
* ` (3,2) @ (2,3) ` will work

2. The resulting matrix has the shape of the **outer dimension**
* `(2,3) @ (3,2)` shape will be `(2,2)`
* `(3,2) @ (2,3)` shape will be `(3,3)`

In [ ]:
import torch
tensor = torch.arange(start=1, end =4)
print(tensor*tensor)

tensor([1, 4, 9])


In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
%%time
value = 0

for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 140 µs, sys: 1.95 ms, total: 2.09 ms
Wall time: 10.2 ms


In [ ]:
# Matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 292 µs, sys: 42 µs, total: 334 µs
Wall time: 5.02 ms


tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

### Two rules of matrix




In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))
# shape = (2,2)

tensor([[1.3673, 0.3838],
        [0.3330, 0.1062]])

In [ ]:
torch.matmul(torch.rand(3,10), torch.rand(10,3))
# shape = (3,3)

tensor([[1.6255, 1.8806, 2.2961],
        [2.2139, 2.7600, 2.5261],
        [2.2766, 2.9286, 2.6924]])

In [ ]:
torch.matmul(torch.rand(5,2), torch.rand(2,5))
# shape = (5,5)

tensor([[0.0961, 0.2222, 0.2389, 0.0253, 0.4309],
        [0.1390, 0.2597, 0.3322, 0.0520, 0.5564],
        [0.1346, 0.3712, 0.3472, 0.0204, 0.6683],
        [0.1229, 0.2686, 0.3020, 0.0362, 0.5340],
        [0.1236, 0.2047, 0.2899, 0.0528, 0.4664]])

### One of the most common error in deel learning: shape errors


In [ ]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],[3,4],[5,6]])

tensor_B = torch.tensor([
    [7,10],
    [8,11],
    [9,12]
  ])



To fix the shape of the tensors using a **transpose**
A **transpose** switches the axis or dimension fo the given tensor

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed

torch.matmul(tensor_A, tensor_B.T) # shape = (3,3)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum, etc(tensor argument)

In [ ]:
x = torch.arange(1,100,10, dtype=torch.long)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# Find max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# Find mean

torch.mean(x.type(torch.float16)), x.type(torch.float16).mean()

(tensor(46., dtype=torch.float16), tensor(46., dtype=torch.float16))

In [ ]:
# Find sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the position of min and max


In [ ]:
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

### reshaping, stacking, squeezing and unsqueezing tensors



* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the orginal tensor
* Stacking - combine multiple tensors on top of the each other (vstack) or side by side (hstack)
* Squeeze - removes all one dimensions from a tensor
* unsqueeze - add a one dimension to a target tensor
* Permute - return a view of the input with dimension permuted (swapped) in a certain way


In [ ]:
x = torch.arange(1,10, dtype= torch.float16)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16),
 torch.Size([9]))

In [ ]:
# add an extra dimension

x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=torch.float16),
 torch.Size([1, 9]))

In [ ]:
# Change the view

z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=torch.float16),
 torch.Size([1, 9]))

In [ ]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=torch.float16),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16))

In [ ]:
# Stack tensors on top of each other
x_stack = torch.stack([x,x,x,x], dim=1)
x_stack

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]], dtype=torch.float16)

In [ ]:
# torch.squreeze() - remove all sinagle dimensions from a target tensor

x_reshape.shape


torch.Size([1, 9])

In [ ]:
x_reshape.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)

In [ ]:
x_reshape.squeeze().shape

torch.Size([9])

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target

print(x_reshape.squeeze())
print(x_reshape.squeeze().shape)

x_squeeze= x_reshape.squeeze()

x_unsqueeze = x_squeeze.unsqueeze(dim=0)

print(x_unsqueeze)
print(x_unsqueeze.shape)


tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)
torch.Size([9])
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=torch.float16)
torch.Size([1, 9])


In [ ]:
#@title
# torch.permute - rearrange the dimension of a target tensor

x_orangial = torch.rand(size=(224,224,3))
x_orangial.shape

torch.Size([224, 224, 3])

In [ ]:
# permute the original tensor to rearrange the axis or dim
x_permute = x_orangial.permute(2,0,1)

In [ ]:
print(f"previous shape: {x_orangial.shape}")
print(f"new shape: {x_permute.shape}")

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


### Selecting data (Indexing)

In [ ]:
import torch

x = torch.arange(1,10).reshape(1,3,3)

x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0,0]
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0,0,0]

tensor(1)

In [ ]:
x[0][2][-1]

tensor(9)

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[: ,: ,1 ]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

### Pytorch and numpy

In [ ]:
import numpy as np
import torch

* Data in numpy want in pytorch tensor -> `torch.torch.from_numpy(ndarray)`
* Pytorch tensor -> NumPy -> torch.Tensor.numpy()


In [ ]:
# numpy to tensor
array = np.arange(1,8)
tensor = torch.from_numpy(array).type(torch.float32)

In [ ]:
tensor


tensor([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
# tensor to numpy

numpy_tensor = tensor.numpy()

numpy_tensor

array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)

### Reproducibility (trying to take random out of random)

`Start with random numbers -> tensor operations -> update random numbers to try and make them better representstion of data -> again -> again...`


In [ ]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9542, 0.3066, 0.7161, 0.8778],
        [0.7787, 0.4415, 0.4874, 0.2831],
        [0.7245, 0.8339, 0.9628, 0.4098]])
tensor([[0.1279, 0.9607, 0.2865, 0.9735],
        [0.3443, 0.6072, 0.1548, 0.7982],
        [0.1480, 0.4929, 0.4799, 0.9242]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


<h1> random seed <h1>

In [ ]:
import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

print(random_tensor_D)
print(random_tensor_C)
print(random_tensor_D == random_tensor_C)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Accessing a GPU


In [ ]:
!nvidia-smi


Sun Jun 25 17:31:06 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

# Putting tensors (and models) on the GPU



In [ ]:
tensor = torch.tensor([1,2,3])

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# Move tensor to GPU

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# Moving tensor on cpu
tensor_on_cpu= tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])

In [ ]:
import torch
torch.__version__

'2.0.1+cu118'